### ISSUE TITLE
Any chance for docker and docker-compose

### ISSUE THREAD

**Issue by kodxana** [rtrevinnoc/FUTURE#1]
I would love to run own instance but if it could be run in docker container.

**Comment by rtrevinnoc** [comment]
Hello!

First of all, thank you very much for your interest, I am really excited!
Regarding using docker, of course, I had not thought about it, but I will be adding it in the course of the following days so that you can run your own server in a container and so can anyone else.

I appreciate your suggestion <3

**Comment by kodxana** [comment]
I would say look how Yacy does that also would be nice to specify websites to crawl.

**Comment by rtrevinnoc** [comment]
HI!

I have added a Dockerfile to the repo 725929706aa0b2997a7f831d841d0c36444f99bd, which allows to create an image based on ubuntu to run FUTURE in a container. It copies the files from the downloaded repository onto the container, and sets everything up to start crawling.

As for specifying which sites to crawl, that can be partially accomplised using the `SEED_URLS` variable in the config.py file, however the crawler will follow links onto other sites, therefore I will be adding a functionality to limit which domains to crawl in the following days.

Thank you very much for your interest <3.
