### ISSUE TITLE
Tag for search resoults that comes from P2P network

### ISSUE THREAD

**Issue by kodxana** [rtrevinnoc/FUTURE#2]
Would be nice to have tag next to the search results that came from P2P network instead of public serax instances.
And also some info how much peers are in network etc.

**Comment by rtrevinnoc** [comment]
Hello!

Yes, that sounds great :) I will be adding some kind of status page accessible through the sidebar in the coming days.
For now, to see currently known peers you can run `python count_peers.py`

Thank you for your suggestion <3.

**Comment by rtrevinnoc** [comment]
Hello!

I had been busy with college work, and I still am quite a bit, nevertheless, I wanted to post a quick update. On 02635a6061de7eb1d8407b4660fd1164ee510c43 I added a page called `/stats` (e.g. wearebuildingthefuture.com/stats) which updates every 15 seconds with some stats from every public node in the network. The design of the stats page is provisional, I think I will be making it prettier, although I quite like the "cyberpunk" theme.

Also, I added a searX badge (based on those from https://shields.io/) on 22e374b6c8f58a34c9438c3cde66f8f532b517de, behind every link coming from a searX instance, so that they can be distinguished. It is important to note, that all searX links appear by default on top of those from FUTURE because, for now, given the low number of peers, the quality of the latter is expected to be lower.

I will keep working on these things, with increased attention as soon as I have more time, which I expect to be next week :)
Anyway, thank you for your interest <3
